# Generated by Django 4.1.7 on 2024-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
